const KEYS = [
  {sign:'flat',count:7,major:'変ハ長調',minor:'変イ短調'},
  {sign:'flat',count:6,major:'変ト長調',minor:'変ホ短調'},
  {sign:'flat',count:5,major:'変ニ長調',minor:'変ロ短調'},
  {sign:'flat',count:4,major:'変イ長調',minor:'ヘ短調'},
  {sign:'flat',count:3,major:'変ホ長調',minor:'ハ短調'},
  {sign:'flat',count:2,major:'変ロ長調',minor:'ト短調'},
  {sign:'flat',count:1,major:'ヘ長調',minor:'ニ短調'},
  {sign:'none',count:0,major:'ハ長調',minor:'イ短調'},
  {sign:'sharp',count:1,major:'ト長調',minor:'ホ短調'},
  {sign:'sharp',count:2,major:'ニ長調',minor:'ロ短調'},
  {sign:'sharp',count:3,major:'イ長調',minor:'嬰ヘ短調'},
  {sign:'sharp',count:4,major:'ホ長調',minor:'嬰ハ短調'},
  {sign:'sharp',count:5,major:'ロ長調',minor:'嬰ト短調'},
  {sign:'sharp',count:6,major:'嬰ヘ長調',minor:'嬰ニ短調'},
  {sign:'sharp',count:7,major:'嬰ハ長調',minor:'嬰イ短調'}
];
const SHARP_Y=[55,85,45,75,105,65,95]; // F5 C5 G5 D5 A4 E5 B4, staff lines y=55,75,95,115,135
const FLAT_Y=[95,65,105,75,115,85,125]; // B4 E5 A4 D5 G4 C5 F4
const $=selector=>document.querySelector(selector);
const state={mode:'read',kind:'major',key:null,targetKind:'major',question:0,correct:0,streak:0,answered:false,selectedSign:null,selectedCount:null,lastKey:null};
function choice(array){return array[Math.floor(Math.random()*array.length)]}
function shuffle(array){return [...array].sort(()=>Math.random()-.5)}
function signatureText(key){return key.count===0?'調号なし':`${key.sign==='sharp'?'♯':'♭'} ${key.count}個`}
function sharp(x,y){return `<g transform="translate(${x} ${y})" fill="none" stroke="#334155"><path d="M5 -20v38 M17 -22v38" stroke-width="2.6"/><path d="M0 -5l23 -5 M0 8l23 -5" stroke-width="5"/></g>`}
function flat(x,y){return `<g transform="translate(${x} ${y})" fill="none" stroke="#334155" stroke-width="2.5" stroke-linecap="round"><path d="M5 -38v46 C8 -3 23 -12 23 -3 C23 6 13 13 5 17"/></g>`}
function clef(){return `<g fill="none" stroke="#334155" stroke-linecap="round" stroke-linejoin="round"><path d="M53 156 C50 138 42 115 40 87 C37 61 53 37 64 27 C77 15 83 26 78 42 C73 59 57 72 45 86 C25 107 23 125 36 135 C49 145 73 141 79 124 C85 106 75 94 61 96 C48 98 44 115 54 121 C61 125 70 120 69 112" stroke-width="3.3"/><path d="M54 156 C57 168 52 175 46 173 C41 171 41 164 46 161" stroke-width="2.7"/></g>`}
function staffSvg(key,placeholder=false){let lines=[55,75,95,115,135].map(y=>`<line x1="20" x2="590" y1="${y}" y2="${y}" stroke="#94a3b8" stroke-width="1.35"/>`).join('');let glyphs='';if(key&&key.count){const ys=key.sign==='sharp'?SHARP_Y:FLAT_Y;glyphs=Array.from({length:key.count},(_,i)=>key.sign==='sharp'?sharp(110+i*31,ys[i]):flat(110+i*31,ys[i])).join('')}return `<svg viewBox="0 0 610 185" role="img" aria-label="ト音記号、${placeholder?'解答用の調号':signatureText(key)}" preserveAspectRatio="xMidYMid meet"><rect width="610" height="185" fill="#fff"/>${lines}${clef()}${glyphs}</svg>`}
function setStaff(key,placeholder=false){$('#staff').innerHTML=staffSvg(key,placeholder);$('#staff').setAttribute('aria-label',`ト音記号の五線譜。${placeholder?'調号を選んでください':signatureText(key)}`)}
function newQuestion(){const pool=KEYS.filter(k=>k!==state.lastKey);state.key=choice(pool);state.lastKey=state.key;state.targetKind=state.kind==='mix'?choice(['major','minor']):state.kind;state.question++;state.answered=false;state.selectedSign=null;state.selectedCount=null;$('#question-number').textContent=`QUESTION ${String(state.question).padStart(2,'0')}`;$('#mode-caption').textContent=state.mode==='read'?'調号から調名へ':'調名から調号へ';$('#prompt').textContent=state.mode==='read'?`この調号は何${state.targetKind==='major'?'長調':'短調'}？`:`${state.key[state.targetKind]} の調号は？`;$('#staff-hint').textContent=state.mode==='read'?'譜面の調号を見て答えを選んでください。':'記号と数を選ぶと、譜面に調号が表示されます。';$('#read-controls').hidden=state.mode!=='read';$('#write-controls').hidden=state.mode!=='write';$('#feedback').hidden=true;$('#feedback').className='feedback';$('#next-button').hidden=true;$('#answer-step').textContent=state.mode==='read'?'選択式':'記号＋数';setStaff(state.mode==='read'?state.key:null,state.mode==='write');if(state.mode==='read')renderChoices();else renderBuilder()}
function renderChoices(){const answer=state.key[state.targetKind];const nearby=KEYS.filter(k=>k!==state.key).sort((a,b)=>Math.abs(a.count-state.key.count)-Math.abs(b.count-state.key.count));const distractors=shuffle(nearby.slice(0,7)).slice(0,3).map(k=>k[state.targetKind]);const values=shuffle([answer,...distractors]);$('#choices').replaceChildren(...values.map((value,i)=>{const button=document.createElement('button');button.type='button';button.className='choice-button';button.dataset.answer=value;button.innerHTML=`<span class="choice-index">${String.fromCharCode(65+i)}</span>`;button.append(document.createTextNode(value));button.addEventListener('click',()=>checkAnswer(value===answer,button));return button}))}
function renderBuilder(){const signArea=$('#sign-choices');signArea.replaceChildren(...[{id:'none',label:'なし'},{id:'sharp',label:'♯'},{id:'flat',label:'♭'}].map(item=>{const button=document.createElement('button');button.type='button';button.className='builder-option'+(item.id==='none'?' zero':'');button.textContent=item.label;button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{state.selectedSign=item.id;state.selectedCount=item.id==='none'?0:null;updateBuilder()});button.dataset.sign=item.id;return button}));const numberArea=$('#count-choices');numberArea.replaceChildren(...Array.from({length:7},(_,i)=>{const button=document.createElement('button');button.type='button';button.className='builder-option';button.textContent=i+1;button.dataset.count=i+1;button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{state.selectedCount=i+1;updateBuilder()});return button}));updateBuilder()}
function updateBuilder(){document.querySelectorAll('[data-sign]').forEach(b=>{const selected=b.dataset.sign===state.selectedSign;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.disabled=state.answered});document.querySelectorAll('[data-count]').forEach(b=>{const selected=Number(b.dataset.count)===state.selectedCount&&state.selectedSign!=='none';b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.disabled=state.answered||!state.selectedSign||state.selectedSign==='none'});$('#submit-signature').disabled=state.answered||state.selectedSign===null||state.selectedCount===null;setStaff(state.selectedSign&&state.selectedCount!==null?{sign:state.selectedSign,count:state.selectedCount}:null,true)}
function checkAnswer(isCorrect,button){if(state.answered)return;state.answered=true;if(isCorrect){state.correct++;state.streak++}else state.streak=0;$('#correct-count').textContent=state.correct;$('#streak-count').textContent=state.streak;const answer=state.key[state.targetKind];const detail=`${signatureText(state.key)} は ${state.key.major} / ${state.key.minor} の調号です。`;const feedback=$('#feedback');feedback.innerHTML=`<strong>${isCorrect?'正解！':'おしい！ 正解は '+(state.mode==='read'?answer:signatureText(state.key))}</strong><span>${detail}</span>`;feedback.classList.toggle('wrong',!isCorrect);feedback.hidden=false;$('#next-button').hidden=false;if(state.mode==='read'){document.querySelectorAll('.choice-button').forEach(b=>{b.disabled=true;if(b.dataset.answer===answer)b.classList.add('correct')});if(button&&!isCorrect)button.classList.add('incorrect')}else{$('#submit-signature').disabled=true;document.querySelectorAll('.builder-option').forEach(b=>b.disabled=true);setStaff(state.key)}}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.mode===state.mode)return;state.mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});newQuestion()}));
document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.kind===state.kind)return;state.kind=button.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});newQuestion()}));
$('#submit-signature').addEventListener('click',()=>checkAnswer(state.selectedSign===state.key.sign&&state.selectedCount===state.key.count));
$('#next-button').addEventListener('click',newQuestion);
newQuestion();

// The same quiz actions can be used by browsers that support WebMCP.
if (document.modelContext?.registerTool) {
  const context=document.modelContext;
  const register=tool=>{try{Promise.resolve(context.registerTool(tool)).catch(()=>{})}catch(_error){}};
  register({name:'submit_quiz_answer',title:'調号クイズに答える',description:'現在の問題に回答し、画面に正誤を表示します。調号から調名への問題では調名、逆方向では記号と数を指定します。',inputSchema:{type:'object',properties:{name:{type:'string'},sign:{type:'string',enum:['none','sharp','flat']},count:{type:'integer',minimum:0,maximum:7}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(state.answered)throw Error('この問題は回答済みです。');if(state.mode==='read'){const button=[...document.querySelectorAll('.choice-button')].find(b=>b.dataset.answer===input.name);if(!button)throw Error('表示されている調名を指定してください。');button.click()}else{if(!['none','sharp','flat'].includes(input.sign)||!Number.isInteger(input.count)||input.count<0||input.count>7||(input.sign==='none'&&input.count!==0)||(input.sign!=='none'&&input.count===0))throw Error('調号の記号と数を正しく指定してください。');state.selectedSign=input.sign;state.selectedCount=input.count;updateBuilder();$('#submit-signature').click()}return{correct:$('#feedback').classList.contains('wrong')===false,answer:state.key[state.targetKind],signature:signatureText(state.key)}}});
  register({name:'start_next_quiz_question',title:'次の調号問題へ',description:'答え合わせの後に次の問題を表示します。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){if(!state.answered)throw Error('先に現在の問題へ回答してください。');newQuestion();return{question:state.question,mode:state.mode,kind:state.targetKind}}});
}
